name: Deploy Laravel App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull latest code
        run: |
          git pull origin master

      - name: Setup
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Generate app key
        run: php artisan key:generate

      - name: Run migrations and seed database
        run: |
          php artisan migrate --force
          php artisan db:seed --force

      - name: Create storage link
        run: php artisan storage:link

      - name: Deploy Docker
        run: |
          docker-compose down --remove-orphans
          docker-compose up -d --scale app=3 --build
          

          